function createcolorbar(axes1)
%CREATECOLORBAR(axes1)
%  AXES1:  colorbar axes

%  Auto-generated by MATLAB on 23-Apr-2020 02:01:29

% Create colorbar
colorbar(axes1,'Position',...
    [0.868702290076336 0.124737945492663 0.0274809160305344 0.31236897274633],...
    'TickLabels',{'-2.5','-2.0','-1.5','-1.0','-0.5','0','0.5','1','1.5','2.0','2.5'});

end 